### ISSUE TITLE
[Security] Software/Framework versions

### ISSUE THREAD

**Issue by Ocimum-basilicum** [Ecoxl/celero#16]
Another security flaw we need to think about our core Frameworks and PHP versions. 
As far as I can tell we use:

- Codeigniter 2.1.4, the latest available version of Codeigniter is 3.1.6
- PHP 5.6.30 (still supported though), the latest available version is 7.0
- JQuery 1.10.2 (we have at least 6 different JQuery libraries under /assets), the latest available version is 3.2.1 
- others? 

We need to think about getting these libraries direct from the source. We cant guarantee that old versions are secure!

**Comment by tcgumus** [comment]
Codeigniter 2 and 3 is created by different companies which they are poorly similar. If you want to update it to the next level we will need a lot time to check every deprecated function and method and attributes. 

We can use latest jquery always. These old one are required by the geo tools (as zeynel said). We can also use never pho versions but we need to check all php settings and http configuration. Deprecated libraries etc. Which by the way i cant make it from here since i cant connect to server. I will talk this issue with dirk and share the ideas.

**Comment by Ocimum-basilicum** [comment]
CI and JS libraries got update 👍 

Only PHP left. If CELERO continues to live past 2018 we need to think about upgrading PHP. Support and updates (incl. security!) for PHP5 ends Dec. 2018.

**Comment by Ocimum-basilicum** [comment]
CELERO runs on PHP7 now! 
All used framework versions are updated.
